#!/usr/bin/env bash
# ============================================================
# Build script for the Zola site.
# - Writes data/build.toml with the current UTC build timestamp.
# - Invokes `zola build`.
#
# Zola does NOT expose a built-in `now()` Tera function, so we
# inject the build time through this side-channel and the
# template reads it via `load_data(path="data/build.toml")`.
# ============================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Generate build timestamp
build_iso="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
build_human="$(date -u +"%Y-%m-%d")"
build_unix="$(date -u +"%s")"

mkdir -p data

# Write the build stamp. printf (not a heredoc) avoids shell backtick /
# command-substitution surprises in the embedded comment.
printf '# AUTO-GENERATED by scripts/build.sh — do not edit by hand.\n# Re-generated on every zola build.\n\niso   = "%s"\nhuman = "%s"\nunix  = "%s"\n' \
  "$build_iso" "$build_human" "$build_unix" > data/build.toml

echo "[build.sh] build stamp -> ${build_iso}"

# Fetch GitHub contributions at build time (soft-fail on missing token / network)
node "$(dirname "${BASH_SOURCE[0]}")/fetch_github_contributions.mjs" || true

# Run zola with whatever args were passed (typically: build / serve)
exec zola "$@"
