#!/usr/bin/env bash
# ============================================================
# Build script for the Zola site.
# - Writes data/build.toml with the current UTC build timestamp.
# - Invokes `zola build`.
#
# Zola does NOT expose a built-in `now()` Tera function, so we
# inject the build time through this side-channel and the
# template reads it via `load_data(path="data/build.toml")`.
# ============================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Generate build timestamp
build_iso="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
build_human="$(date -u +"%d %b %Y")"
build_unix="$(date -u +"%s")"

mkdir -p data

cat > data/build.toml <<EOF
# AUTO-GENERATED by scripts/build.sh — do not edit by hand.
# Re-generated on every `zola build`.

iso   = "${build_iso}"
human = "${build_human}"
unix  = "${build_unix}"
EOF

echo "[build.sh] build stamp -> ${build_iso}"

# Run zola with whatever args were passed (typically: build / serve)
exec zola "$@"
